---
title: "Untitled"
output: html_document
date: "2024-02-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. data load
```{r}
library(tidyverse)
library(openxlsx)
library(vegan)
library(survival)
library(survminer)
library(forestploter)
```

```{r}
# taxa
pr <- readRDS("../../../2.SourceData/00.SourceData/Kraken2.UCAN.WGS.Splited.rds")
a <-  readRDS("../../../2.SourceData/00.SourceData/Kraken2.ICAM.WGS.rds")
b <-  readRDS("../../../2.SourceData/00.SourceData/16S.ICAM.rds")
pr$ICAM.Tumor.WGS <- a

b1 <- b$NAT$Genus
b2 <- b$Tumor$Genus
colnames(b1) <- gsub("D_5","g",colnames(b1))
colnames(b2) <- gsub("D_5","g",colnames(b2))

pr$ICAM.Tumor.16S <- b2
pr$ICAM.NAT.16S <- b1


#pr <- lapply(pr,function(x){
#  x <- x[,grep("g__",colnames(x))]
#  x <- sweep(x,1,rowSums(x),"/")
#})




taxa <- lapply(pr,function(x) x[,"g__Akkermansia",drop=F])

# reads number
nReads <- readRDS("../../../2.SourceData/00.SourceData/ReadsNumber.UCAN_ICAM.rds")
```


```{r}
# phenotypes
phe.icam <- readRDS("../../../2.SourceData/00.SourceData/phenotype.ICAM.rds")
phe.ucan <- read.csv("../../../2.SourceData/01.phe/20230727-CRC-SW.20230704-v5.clinical.csv",row.names = 1)
```


## 2. data process

```{r}
# confounders
phe.ucan$Tumor_Site <- ifelse(phe.ucan$Tumor_Site=="Right_Colon","Right","Left")
phe.ucan$Tumor_Site <- factor(phe.ucan$Tumor_Site,levels = c("Right","Left"))
phe.ucan$Age <- phe.ucan$Age_At_Diagnosis

adj.uu <- phe.ucan[rownames(taxa$UU.Tumor),c("Tumor_Site","Tumor_Grade","Tumor_Stage","Age","Treatment_After_Surgery")]
adj.um <- phe.ucan[rownames(taxa$UM.Tumor),c("Tumor_Site","Tumor_Grade","Tumor_Stage","Age","Treatment_After_Surgery")]
adj.icam <- phe.icam[,c("Location","AJCC_path_stage","Age")]


# without stage IV
adj.uu <- adj.uu[which(adj.uu$Tumor_Stage!="IV"),]
adj.um <- adj.um[adj.um$Tumor_Stage!="IV",]
adj.icam <- adj.icam[adj.icam$AJCC_path_stage !=4,]
colnames(adj.icam) <- c("Tumor_Site","Tumor_Stage","Age")
adj.icam$Tumor_Site <- factor(adj.icam$Tumor_Site)
adj.icam$Tumor_Stage <- factor(adj.icam$Tumor_Stage)
```

```{r}
# prognosis
dat.uu <- phe.ucan[rownames(adj.uu),c("OS_5Years_with_censored_update","OS_Status_5Years_with_censored_update","RFS_Status_5Years_with_censored","RFS_5Years_with_censored")]
dat.um <- phe.ucan[rownames(adj.um),c("OS_5Years_with_censored_update","OS_Status_5Years_with_censored_update","RFS_Status_5Years_with_censored","RFS_5Years_with_censored")]
colnames(dat.uu) <- colnames(dat.um) <- c("OS_time","OS_status","RFS_status","RFS_time")

dat.icam <- phe.icam[rownames(adj.icam),c("OS_status","OS_time","PFS_status","PFS_time")]
```

```{r}
# combine data
dat.uu.t <- cbind(dat.uu,adj.uu[rownames(dat.uu),,drop=F],taxa$UU.Tumor[rownames(dat.uu),,drop=F])
dat.um.t <- cbind(dat.um,adj.um[rownames(dat.um),,drop=F],taxa$UM.Tumor[rownames(dat.um),,drop=F])
dat.icam.t1 <- cbind(dat.icam,adj.icam[rownames(dat.icam),,drop=F],taxa$ICAM.Tumor.16S[rownames(dat.icam),,drop=F])

a <- dat.icam[rownames(dat.icam) %in% rownames(taxa$ICAM.Tumor.WGS),]
dat.icam.t2 <- cbind(dat.icam[rownames(a),],adj.icam[rownames(a),,drop=F],taxa$ICAM.Tumor.WGS[rownames(a),,drop=F])

a <- dat.uu[rownames(dat.uu) %in% rownames(taxa$UU.NAT),]
dat.uu.n <- cbind(dat.uu[rownames(a),],adj.uu[rownames(a),,drop=F],taxa$UU.NAT[rownames(a),,drop=F])
dat.um.n <- cbind(dat.um,adj.um[rownames(dat.um),,drop=F],taxa$UM.NAT[rownames(dat.um),,drop=F])
dat.icam.n1 <- cbind(dat.icam,adj.icam[rownames(dat.icam),,drop=F],taxa$ICAM.NAT.16S[rownames(dat.icam),,drop=F])

dat.uu.t$ReadsNumber <- nReads$UU.Tumor[rownames(dat.uu.t),4]
dat.uu.n$ReadsNumber <- nReads$UU.NAT[rownames(dat.uu.n),4]
dat.um.t$ReadsNumber <- nReads$UM.Tumor[rownames(dat.um.t),4]
dat.um.n$ReadsNumber <- nReads$UM.NAT[rownames(dat.um.n),4]

dat.icam.t2$ReadsNumber <- nReads$ICAM.Tumor.WGS[rownames(dat.icam.t2),4]

```

## 3.HR
```{r}

HR <- function(data,x,f,adj=NULL){
  x1 <- make.names(x)
  data[,x1] <- data[,x]
  data <- data[!is.na(data[,x1]),]
  lab.x <- paste(x1,collapse = "+")
  formula <- paste0(f,lab.x)
  if(!is.null(adj)){
    lab.adj <- paste(adj,collapse = "+")
    formula <- paste0(formula,"+",lab.adj)
  }
  formula <- as.formula(formula)
  #print(formula)
  fit <- coxph(formula,data=data)
  a <- summary(fit)
  # output
  out <- cbind(
    a$coefficients[,c(1,4,5),drop=F],
    a$conf.int[,c(1,3,4),drop=F]
  )
  colnames(out) <- c("coef","z","P","HR","lower.95","upper.95")
  out <- out %>%
    as.data.frame() %>%
    rownames_to_column(var = "x") %>%
    mutate(
      HR2 = paste0(round(HR,2)," (",round(lower.95,2)," to ",round(upper.95,2),")")
    )
  if(is.factor(data[,x])){
      n <- table(data[,x])
      out$N1 <- n[1]
      out$N2 <- n[2]
      out$N <- paste0(out$N2," vs. ",out$N1)
    }
  out <- out[1,]
}
multiHR <- function(dat,f,x,adj){
  a <- lapply(x,HR,data=dat,f=f,adj=adj)
  a <- do.call(rbind,a)
  a$FDR <- p.adjust(a$P,method = "BH")
  a
}
HR_Forest = function(dat,xlim=c(0.5,10)){
  dat$` ` <- paste(rep(" ", 20), collapse = " ")
  colnames(dat)[colnames(dat)=="HR2"] <- "HR (95% CI)"
  dat$P[is.na(dat$P)] <- ""
  dat$FDR[is.na(dat$FDR)] <- ""
  dat$N[is.na(dat$N)] <- ""
  forest(
    data = dat[,c(1,11,13,8,4),drop=F],
    est=dat$HR,
    lower = dat$lower.95,
    upper = dat$upper.95,
    ci_column = 3,
    ref_line = 1,
    size=0.6,
    x_trans = "log",
    ticks_at = c(0.5,1,2,3,4,5,6,7,8,9),
    xlim =xlim,
    xlab = c("Hazard ratio")
  )
}


```

```{r,warning=F}
f1 <- "Surv(OS_time,OS_status)~"
f2 <- "Surv(RFS_time,RFS_status)~"
f3 <- "Surv(PFS_time,PFS_status)~"
```


```{r}
addGroup <- function(dat){
  dat$g__Akkermansia[is.na(dat$g__Akkermansia)] <- 0
  dat$continuous <- dat$g__Akkermansia
  dat$continuous[dat$continuous==0] <- min(dat$continuous[dat$continuous>0])/2
  dat$continuous <- scale(log10(dat$continuous))
  l <- seq(0,0.1,0.001)
  for(x in l){
    dat[,paste0("Cut",x)] <- ifelse(dat$g__Akkermansia>=x,"1","0")
    dat[,paste0("Cut",x)] <- factor(dat[,paste0("Cut",x)])
  }
  dat
}

dat.uu.t <- addGroup(dat.uu.t)
dat.um.t <- addGroup(dat.um.t)
dat.icam.t1 <- addGroup(dat.icam.t1)
dat.uu.n <- addGroup(dat.uu.n)
dat.um.n <- addGroup(dat.um.n)
dat.icam.n1 <- addGroup(dat.icam.n1)
dat.icam.t2 <- addGroup(dat.icam.t2)
```

```{r,warning=F}
x <- paste0("Cut",seq(0,0.1,0.001))
x <- x[-1]

n <- lapply(x,function(a,b){
  table(b[,a])
},b=dat.uu.n)
n <- do.call(rbind,n)
rownames(n) <- gsub("Cut","",x)
n <- as.data.frame(n)

r1 <- multiHR(dat.uu.t,f = f1,x=x,adj = NULL)
r2 <- multiHR(dat.um.t,f = f1,x=x,adj = NULL)
r3 <- multiHR(dat.icam.t1,f = f1,x=x,adj = NULL)
r4 <- multiHR(dat.icam.t2,f = f1,x=x,adj = NULL)
hr.t <- list(UU=r1,UM=r2,ICAM.16S=r3,ICAM.WGS=r4)

r1 <- multiHR(dat.uu.n,f = f1,x=x,adj = NULL)
r2 <- multiHR(dat.um.n,f = f1,x=x,adj = NULL)
r3 <- multiHR(dat.icam.n1,f = f1,x=x,adj =NULL)
hr.n <- list(UU=r1,UM=r2,ICAM.16S=r3)
```

```{r}
HRForest <- function(dat){
  dat <- dat[-1,]
  dat$x <- gsub("Cut","",dat$x)
  dat$x <- gsub("1$","",dat$x)
  x.max <- dat$x[which.max(dat$HR)]
  ggplot(dat,aes(x,y=HR))+
    geom_point()+
    geom_errorbar(aes(ymin=lower.95,ymax=upper.95),width=0.5)+
    geom_hline(yintercept = 1,linetype="dashed")+
    annotate("text",label=x.max,x=x.max,y=Inf,vjust=1.2,size=4)+
    scale_x_discrete(breaks=as.character(seq(0,0.1,0.005)))+
    xlab("Cutoff")+
    theme_bw()+
    theme(
      axis.text = element_text(colour = 1,size=14),
      axis.text.x = element_text(angle = 270,vjust = 0.5,hjust = 0),
      panel.grid.major.x   = element_blank(),
      panel.grid.minor.x = element_blank(),
      strip.text = element_text(size = 14),
      legend.title = element_text(size = 14),
      legend.text = element_text(size = 14)
    )
}

HRForest(hr.n$UU)
HRForest(r1)

p <- lapply(hr.n,HRForest)
ggarrange(plotlist = p,nrow = 3,ncol = 1,align = "hv")

p <- lapply(hr.t,HRForest)
ggarrange(plotlist = p,nrow = 4,ncol = 1,align = "hv")

```



```{r}
HRForest2 <- function(dat){
  dat$x <- gsub("Cut","",dat$x)
  dat$x <- gsub("1$","",dat$x)
  x.max <- dat$x[which.max(dat$HR)]
  ggplot(dat,aes(x,y=HR,color=Group))+
    geom_point()+
    #geom_errorbar(data=dat[dat$Group=="NAT",],aes(ymin=lower.95,ymax=upper.95),width=0.5,alpha=0.2,linewidth=2)+
    #geom_errorbar(data=dat[dat$Group=="Tumor",],aes(ymin=lower.95,ymax=upper.95),width=0.5,alpha=0.2,linewidth=0.75)+
    geom_line(aes(group=Group))+
    geom_hline(yintercept = 1,linetype="dashed")+
    geom_vline(xintercept = "0.05")+
    #annotate("text",label=x.max,x=x.max,y=Inf,vjust=1.2,size=4)+
    scale_x_discrete(breaks=as.character(c(0,0.025,0.05,0.07)))+
    scale_y_continuous(breaks = c(0,0.5,1,1.5,2,2.5),limits = c(0,2.5))+
    scale_color_manual(values = c("#848CCF","#BE5683"))+
    xlab("Cutoff")+
    theme_bw()+
    theme(
      axis.text = element_text(colour = 1,size=14),
      #axis.text.x = element_text(angle = 270,vjust = 0.5,hjust = 0),
      panel.grid = element_blank(),
      strip.text = element_text(size = 14),
      legend.title = element_text(size = 14),
      legend.text = element_text(size = 14),
      legend.position = c(0.01,0.01),
      legend.justification = c(0,0)
    )
}

a <- hr.n$UU
b <- hr.t$UU
a$Group <- "NAT"
b$Group <- "Tumor"
a <- rbind(a,b)
a <- a[a$x %in% paste0("Cut",seq(0.001,0.07,0.001),"1"),]
a[nrow(a)+1,] <- NA
a[nrow(a)+1,1] <- "Cut01"
HRForest2(a)
ggsave("Dot.HR.Tumor_NAT.pdf",width = 7,height = 3.5)
```






```{r}
# cutoff = 0.05

# OS
r1 <- multiHR(dat.uu.n,f = f1,x="Cut0.019",adj = c(colnames(adj.uu),"ReadsNumber"))
r2 <- multiHR(dat.um.n,f = f1,x="Cut0.019",adj = c(colnames(adj.um),"ReadsNumber"))
r3 <- multiHR(dat.icam.n1,f = f1,x="Cut0.019",adj = c(colnames(adj.icam)))
#RFS
r4 <- multiHR(dat.uu.n,f = f2,x="Cut0.019",adj = c(colnames(adj.uu),"ReadsNumber"))
r5 <- multiHR(dat.um.n,f = f2,x="Cut0.019",adj = c(colnames(adj.um),"ReadsNumber"))
r6 <- multiHR(dat.icam.n1,f = f3,x="Cut0.019",adj = c(colnames(adj.icam)))

r <- rbind(
  list("OS",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),
  r1,r2,r3,
  list("RFS",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),
  r4,r5,
  list("PFS",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),
  r6
)
r$x <- c("OS","    UU","    UM","    AC-ICAM",
         "RFS","    UU","    UM",
         "PFS","    AC-ICAM")
r$P <- round(r$P,3)
r$P[is.na(r$P)] <- ""
r$HR2[is.na(r$HR2)] <- ""
p <- HR_Forest(r)
print(p)
pdf("forest.Akkermansia.pdf",width = 10,height = 5)
print(p)
dev.off()

out.n <- r
```

```{r}
# cutoff = 0.05

# OS
r1 <- multiHR(dat.uu.t,f = f1,x="Cut0.05",adj = c(colnames(adj.uu),"ReadsNumber"))
r2 <- multiHR(dat.um.t,f = f1,x="Cut0.05",adj = c(colnames(adj.um),"ReadsNumber"))
r3 <- multiHR(dat.icam.t1,f = f1,x="Cut0.05",adj = c(colnames(adj.icam)))
#RFS
r4 <- multiHR(dat.uu.t,f = f2,x="Cut0.05",adj = c(colnames(adj.uu),"ReadsNumber"))
r5 <- multiHR(dat.um.t,f = f2,x="Cut0.05",adj = c(colnames(adj.um),"ReadsNumber"))
r6 <- multiHR(dat.icam.t1,f = f3,x="Cut0.05",adj = c(colnames(adj.icam)))

r <- rbind(
  list("OS",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),
  r1,r2,r3,
  list("RFS",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),
  r4,r5,
  list("PFS",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),
  r6
)
r$x <- c("OS","    UU","    UM","    AC-ICAM",
         "RFS","    UU","    UM",
         "PFS","    AC-ICAM")
r$P <- round(r$P,3)
r$P[is.na(r$P)] <- ""
r$HR2[is.na(r$HR2)] <- ""

out.t <- r

out <- cbind(out.n,out.t)
write.xlsx(out,"HR.Akker.Cut0.05.xlsx")
```

```{r}
# survival
survplotFunction <- function(dat,x,f,title,xid){
  dat$OS_time <- dat$OS_time/365
  dat$RFS_time <- dat$RFS_time/365
  f <- paste0(f,x)
  p <- 
  ggsurvplot(
    fit = survfit(as.formula(f), data = dat),
    data=dat,pval = F,
    legend="none",
    cumevents = T,title=title,
    palette = c("#4682B4","#C06C84")
  )
  p$plot <- p$plot + 
    geom_vline(xintercept = xid,linetype="dashed",color=c("#4682B4","#C06C84"))+
    annotate("text",label=xid[1],x=xid[1],y=Inf,vjust=1.2)+
    annotate("text",label=xid[2],x=xid[2],y=Inf,vjust=1.2)
  p
}

xid <- tapply(dat.uu.n$OS_time/365,dat.uu.n$OS_status,median)
xid <- round(xid,2)
p1 <- survplotFunction(dat.uu.n,x="Cut0.05",f1,"UU (NATs)",xid)
xid <- tapply(dat.uu.n$RFS_time/365,dat.uu.n$RFS_status,median)
xid <- round(xid,2)
p2 <- survplotFunction(dat.uu.n,x="Cut0.05",f2,"UU (NATs)",xid)

ggarrange(p1$plot,p2$plot,p1$cumevents,p2$cumevents,nrow = 2,ncol = 2,align = "hv",heights = c(2,1))
ggsave("survival.Akk.v2.pdf",width = 7,height = 4)
```


```{r}
# phenotypes
a <- cbind(dat.uu.n[,"Cut0.05",drop=F],phe.ucan[rownames(dat.uu.n),])
colnames(a)[1] <- "Group"
library(table1)
table1(~ Age + Gender + Tumor_Site + CMS_Subtype + HM_Status + Tumor_Stage | Group, data=a, overall=F, extra.col=list(`P-value`=pvalue)
       )


library(gtsummary)
b <- a[,c("Age","Gender","Tumor_Site","CMS_Subtype","HM_Status","Tumor_Stage","Group")]
tbl <- b %>%
  tbl_summary(by="Group",missing = "no") %>%
  add_p() %>%
  gtsummary::as_tibble() %>% 
  openxlsx::write.xlsx(., "example_gtsummary1.xlsx")



```


```{r}
save.image("HR.Akkermansia.stratified.V3.rd")
load("HR.Akkermansia.stratified.V3.rd")
```




