---
title: "fig5h"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.data
```{r}
library(openxlsx)
library(tidyverse)
library(ggpubr)
library(survival)
library(survminer)
library(forestploter)
```

```{r}
<<<<<<<< HEAD:script/fig5/Fig5i.survival.curve.Rmd
mrs <- readRDS("MRS.UCAN_ICAM.WGS.rds")
a <- readRDS("../../../4.Part4/MRS/MRS.ICAM.16S.rds")
========
mrs <- readRDS("../../data/00.SourceData/MRS.UCAN_ICAM.WGS.rds")
a <- readRDS("../../data/00.SourceData/MRS.ICAM.16S.rds")
>>>>>>>> e8880ac (update figure):script/fig5/Fig5h.MRS.survival.Rmd
mrs$ICAM.Tumor.16S <- a$ICAM.Tumor.16S
mrs$ICAM.NAT.16S <- a$ICAM.NAT.16S

mrs <- lapply(mrs,function(x){
  x$Group = ifelse(x$Index >= median(x$Index),"High MRS","Low MRS")
  x$Group = factor(x$Group,levels = c("Low MRS","High MRS"))
  rownames(x) <- gsub(".*-(U.*)-.*","\\1",rownames(x))
  x
})


```

```{r}
# data
<<<<<<<< HEAD:script/fig5/Fig5i.survival.curve.Rmd
phe.ucan <- read.csv("../../../../2.SourceData/01.phe/20230727-CRC-SW.20230704-v5.clinical.csv",row.names = 1)
phe.icam <- readRDS("../../../../2.SourceData/00.SourceData/phenotype.ICAM.rds")
========
phe.ucan <- read.csv("../../data/01.phe/20230727-CRC-SW.20230704-v5.clinical.csv",row.names = 1)
phe.icam <- readRDS("../../data/00.SourceData/phenotype.ICAM.rds")
>>>>>>>> e8880ac (update figure):script/fig5/Fig5h.MRS.survival.Rmd
phe.ucan$Tumor_Site <- ifelse(phe.ucan$Tumor_Site=="Right_Colon","Right","Left")
phe.ucan$Age <- phe.ucan$Age_At_Diagnosis
phe.icam$AJCC_path_stage <- as.character(phe.icam$AJCC_path_stage)

x <- c("Age","Tumor_Site","Tumor_Stage","Tumor_Grade","Treatment_After_Surgery")

# confounders
adj.uu <- phe.ucan[rownames(mrs$UU.Tumor.WGS),x]
adj.um <- phe.ucan[rownames(mrs$UM.Tumor.WGS),x]
adj.icam <- phe.icam[rownames(mrs$ICAM.Tumor.16S),c("Age","Location","AJCC_path_stage")]
colnames(adj.icam) <- c("Age","Tumor_Site","Tumor_Stage")
adj.icam$Tumor_Site <- factor(adj.icam$Tumor_Site)
adj.icam$Tumor_Stage <- factor(adj.icam$Tumor_Stage)


dat.uu <- phe.ucan[rownames(adj.uu),c("OS_5Years_with_censored_update","OS_Status_5Years_with_censored_update","RFS_Status_5Years_with_censored","RFS_5Years_with_censored","HM_Status")]
dat.um <- phe.ucan[rownames(adj.um),c("OS_5Years_with_censored_update","OS_Status_5Years_with_censored_update","RFS_Status_5Years_with_censored","RFS_5Years_with_censored","HM_Status")]
colnames(dat.uu)[1:4] <- colnames(dat.um)[1:4] <- c("OS_time","OS_status","RFS_status","RFS_time")
dat.icam <- phe.icam[rownames(adj.icam),c("OS_status","OS_time","PFS_status","PFS_time","HM")]

d1 <- cbind(dat.uu,adj.uu[rownames(dat.uu),],mrs$UU.Tumor.WGS[rownames(dat.uu),,drop=F])
d2 <- cbind(dat.um,adj.um[rownames(dat.um),],mrs$UM.Tumor.WGS[rownames(dat.um),,drop=F])
d3 <- cbind(dat.icam[rownames(mrs$ICAM.WGS),],adj.icam[rownames(mrs$ICAM.WGS),],mrs$ICAM.WGS)
d4 <- cbind(dat.uu,adj.uu[rownames(dat.uu),],mrs$UU.NAT.WGS[rownames(dat.uu),,drop=F])
d5 <- cbind(dat.um,adj.um[rownames(dat.um),],mrs$UM.NAT.WGS[rownames(dat.um),,drop=F])
d4 <- d4[!is.na(d4$Index),]

d6 <- cbind(dat.icam[rownames(mrs$ICAM.Tumor.16S),],adj.icam[rownames(mrs$ICAM.Tumor.16S),],mrs$ICAM.Tumor.16S)
d7 <- cbind(dat.icam[rownames(mrs$ICAM.NAT.16S),],adj.icam[rownames(mrs$ICAM.NAT.16S),],mrs$ICAM.NAT.16S)

# reads number
<<<<<<<< HEAD:script/fig5/Fig5i.survival.curve.Rmd
nReads <- read.csv("../../1.data.process/kk2.v2/reads.summary.csv",row.names = 1)
nReads.t <- nReads[nReads$sampleType=="Tumor",]
nReads.n <- nReads[nReads$sampleType=="NAT",]
rownames(nReads.t) <- nReads.t$patientID
rownames(nReads.n) <- nReads.n$patientID

d1$ReadsNumber <- nReads.t[rownames(d1),9]
d2$ReadsNumber <- nReads.t[rownames(d2),9]
d3$ReadsNumber <- nReads.t[rownames(d3),9]
d4$ReadsNumber <- nReads.n[rownames(d4),9]
d5$ReadsNumber <- nReads.n[rownames(d5),9]


dat.t <- rbind(d1,d2)
========
nReads <- readRDS("../../data/00.SourceData/ReadsNumber.UCAN_ICAM.rds")
d1$ReadsNumber <- nReads$UU.Tumor[rownames(d1),1]
d2$ReadsNumber <- nReads$UM.Tumor[rownames(d2),1]
d3$ReadsNumber <- nReads$ICAM.Tumor.WGS[rownames(d3),1]
d4$ReadsNumber <- nReads$UU.NAT[rownames(d4),1]
d5$ReadsNumber <- nReads$UM.NAT[rownames(d5),1]
>>>>>>>> e8880ac (update figure):script/fig5/Fig5h.MRS.survival.Rmd
```



## 2. survival curve

### curve
```{r, fig.width= 16, fig.height=10}
survplotFunction <- function(dat,f,title){
  dat$OS_time <- dat$OS_time/365
  if(any(colnames(dat)=="RFS_time")){
    dat$RFS_time <- dat$RFS_time/365
  }else{
    dat$PFS_time <- dat$PFS_time/365
  }
  
  ggsurvplot(
    fit = survfit(as.formula(f), data = dat),
    data=dat,pval = F,
    legend="none",legend.labs=levels(dat$Group),
    cumevents = T,title=title
  )
}


f <- "Surv(OS_time,OS_status)~Group"
p1 <- survplotFunction(d1,f,"UU (MRS-T)")
p2 <- survplotFunction(d2,f,"UM (MRS-T)")
p3 <- survplotFunction(d3,f,"AC-ICAM (MRS-T)")
p4 <- survplotFunction(d4,f,"UU (MRS-N)")
p5 <- survplotFunction(d5,f,"UM (MRS-N)")

f <- "Surv(RFS_time,RFS_status)~Group"
p6 <- survplotFunction(d1,f,"UU (MRS-T)")
p7 <- survplotFunction(d2,f,"UM (MRS-T)")
p9 <- survplotFunction(d4,f,"UU (MRS-N)")
p10 <- survplotFunction(d5,f,"UM (MRS-N)")

f <- "Surv(PFS_time,PFS_status)~Group"
p8 <- survplotFunction(d3,f,"AC-ICAM (MRS-T)")

<<<<<<<< HEAD:script/fig5/Fig5i.survival.curve.Rmd
res <- arrange_ggsurvplots(
  x = list(p1,p4,p2,p5,p3,p3,p6,p9,p7,p10,p8,p8),print = T,ncol = 6,nrow = 2
)
========
# res <- arrange_ggsurvplots(
#   x = list(p1,p4,p2,p5,p3,p3,p6,p9,p7,p10,p8,p8),print = T,ncol = 6,nrow = 2
# )
# 
# res
#ggsave("survival.MRS.median2.pdf",res,width = 30,height = 10)
>>>>>>>> e8880ac (update figure):script/fig5/Fig5h.MRS.survival.Rmd
```


```{r, fig.width= 16, fig.height=10}
l <- list(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10)
names(l) <- paste0("r",1:10)


r$HR2 <- gsub(" to ","-",r$HR2)
r2$HR2 <- gsub(" to ","-",r2$HR2)

for(x in 1:length(l)){
  tmp <- l[[x]]
  lab <- paste0(
    "HRcat = ",r[x,"HR2"],"\nP = ",formatC(r[x,"P"],digits = 3),
    "\nHRcon = ",r2[x,"HR2"],"\nP = ",formatC(r2[x,"P"],digits = 3)
  )
  print(lab)
  tmp$plot <- tmp$plot +
    annotate("text",label=lab,x=0,y=0.25,hjust=0)
  l[[x]] <- ggarrange(tmp$plot,tmp$cumevents,nrow = 2,ncol = 1,align = "hv",heights = c(2,1))
}

ggarrange(plotlist = l,nrow = 2,ncol = 5)
#ggsave("survival.MRS.median4.pdf",width = 16,height = 8)

```

```{r, fig.width=12}
# 16S
f <- "Surv(OS_time,OS_status)~Group"
p1 <- survplotFunction(d6,f,"AC-ICAM (16S-T)")
p2 <- survplotFunction(d7,f,"AC-ICAM (16S-N)")

f <- "Surv(PFS_time,PFS_status)~Group"
p3 <- survplotFunction(d6,f,"AC-ICAM (16S-T)")
p4 <- survplotFunction(d7,f,"AC-ICAM (16S-N)")


l <- list(p1,p2,p3,p4)
names(l) <- paste0("r",1:4)
for(x in names(l)){
  tmp <- l[[x]]
  l[[x]] <- ggarrange(tmp$plot,tmp$cumevents,nrow = 2,ncol = 1,align = "hv",heights = c(2,1))
}

res <- ggarrange(plotlist = l,nrow = 2,ncol = 2)
res
#ggsave("survival.MRS.ICAM-16S.v2.pdf",res,width = 6,height = 8)
```


<<<<<<<< HEAD:script/fig5/Fig5i.survival.curve.Rmd
========
## 3.adjusted HR

```{r}
HR <- function(data,x,f,adj=NULL){
  x1 <- make.names(x)
  data[,x1] <- data[,x]
  data <- data[!is.na(data[,x1]),]
  lab.x <- paste(x1,collapse = "+")
  formula <- paste0(f,lab.x)
  if(!is.null(adj)){
    lab.adj <- paste(adj,collapse = "+")
    formula <- paste0(formula,"+",lab.adj)
  }
  formula <- as.formula(formula)
  print(formula)
  fit <- coxph(formula,data=data)
  a <- summary(fit)
  # output
  out <- cbind(
    a$coefficients[,c(1,4,5),drop=F],
    a$conf.int[,c(1,3,4),drop=F]
  )
  colnames(out) <- c("coef","z","P","HR","lower.95","upper.95")
  out <- out %>%
    as.data.frame() %>%
    rownames_to_column(var = "x") %>%
    mutate(
      HR2 = paste0(round(HR,2)," (",round(lower.95,2)," to ",round(upper.95,2),")")
    )
  out[1,]
}
HR_Forest <- function(dat){
  dat$` ` <- paste(rep(" ", 20), collapse = " ")
  colnames(dat)[colnames(dat)=="HR2"] <- "HR (95% CI)"
  forest(
    data = dat[,c(1,9,8,4),drop=F],
    est=dat$HR,
    lower = dat$lower.95,
    upper = dat$upper.95,
    ci_column = 2,
    ref_line = 1
  )
}


f1 <- "Surv(OS_time,OS_status)~"
d1$Tumor_Site <- phe.ucan[rownames(d1),"Tumor_Site"]
r1 <- HR(d1,x="Group",f=f1,adj = c(colnames(adj.uu),"ReadsNumber"))
r2 <- HR(d2,x="Group",f=f1,adj = c(colnames(adj.um),"ReadsNumber"))
r3 <- HR(d3,x="Group",f=f1,adj = c(colnames(adj.icam)))
r4 <- HR(d4,x="Group",f=f1,adj = c(colnames(adj.uu),"ReadsNumber"))
r5 <- HR(d5,x="Group",f=f1,adj = c(colnames(adj.um),"ReadsNumber"))
r.os <- rbind(r1,r2,r3,r4,r5)
r.os$x <- c("UU-T","UM-T","AC-ICAM-T","UU-N","UM-N")

f1 <- "Surv(RFS_time,RFS_status)~"
d1$Tumor_Site <- phe.ucan[rownames(d1),"Tumor_Site"]
r1 <- HR(d1,x="Group",f=f1,adj = c(colnames(adj.uu),"ReadsNumber"))
r2 <- HR(d2,x="Group",f=f1,adj = c(colnames(adj.um),"ReadsNumber"))
r4 <- HR(d4,x="Group",f=f1,adj = c(colnames(adj.uu),"ReadsNumber"))
r5 <- HR(d5,x="Group",f=f1,adj = c(colnames(adj.um),"ReadsNumber"))
f1 <- "Surv(PFS_time,PFS_status)~"
r3 <- HR(d3,x="Group",f=f1,adj = c(colnames(adj.icam)))

r.rfs <- rbind(r1,r2,r3,r4,r5)
r.rfs$x <- c("UU-T","UM-T","AC-ICAM-T","UU-N","UM-N")

r <- rbind(r.os,r.rfs)
r$Group <- rep(c("OS","RFS"),each=5)
r
```





```{r}
f1 <- "Surv(OS_time,OS_status)~"
r1 <- HR(d6,x="Group",f=f1,adj=colnames(adj.icam))
r2 <- HR(d7,x="Group",f=f1,adj=colnames(adj.icam))

f1 <- "Surv(PFS_time,PFS_status)~"
r3 <- HR(d6,x="Group",f=f1,adj=colnames(adj.icam))
r4 <- HR(d7,x="Group",f=f1,adj=colnames(adj.icam))

r <- rbind(r1,r2,r3,r4)
r$x <- c("MRS-T (OS)","MRS-N (OS)","MRS-T (PFS)","MRS-N (PFS)")
r
#write.csv(r,"Summary.MRS.HR.median.ICMA.16S.csv")
```


>>>>>>>> e8880ac (update figure):script/fig5/Fig5h.MRS.survival.Rmd


